M48
; DRILL file KiCad 10.0.1 date 2026-06-01T10:25:02
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-06-01T10:25:02+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.500
%
G90
G05
T1
X211.82Y-103.49
X211.82Y-109.27
T2
X129.0Y-63.5
X129.0Y-125.0
X215.0Y-63.5
X215.0Y-124.0
M30
